name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.39.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dac13610ddb0fb22dae4633142680e179d167bad2637383f26fc6a56a50b9b29"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
