name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.65.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "404856a0e2e56c043ab4ec0249fd4016bf934e20ea685d6b8d3677322822788b"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
