name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.40.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b41b0512a1375ced38070346d064a09976bbd2048ee92ef72fa97884ee259e01"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
