name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.50.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c37dcdf85f7d633fbbea4a63d8e199a87526c9efa0507aa0249ca3cee9ae144b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
