name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.48.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4897e4a4fb6e4e70870fff923f72b6ce9ffcd1b37d7859e20a4236546fc450fd"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
