name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.46.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac62499d99d4da12bc25a8a48bd262344fdb25c14676f7c15555ddf2cbaa09fe"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
