name = "Apollo"
author = "Lunar Starstrum <lunar@forsaken-borders.net>"
version = "2.52.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a7cb236de2e3e018686ba49210879fc61e57a746c9c7f010e732e76dd991a6b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
